---

- src: https://github.com/Stouts/Stouts.postfix
  version: origin/develop
  name: Stouts.postfix

- src: https://github.com/Aryamanz29/ansible-ow-influxdb
  version: origin/issue-9/support-for-ubuntu22
  name: ow-influxdb
